python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/aircraft.png --output output/aircraft --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/alarm.png --output output/alarm --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/armor.png --output output/armor --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/backpack.png --output output/backpack --elevation 0  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/box.png --output output/box --elevation 30  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/bread.png --output output/bread --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/bucket.png --output output/bucket --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/busket.png --output output/busket --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/cargo.png --output output/cargo --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/cat.png --output output/cat --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/chili.png --output output/chili --elevation 30  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/crab.png --output output/crab --elevation 30  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/crystal.png --output output/crystal --elevation 0  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/deer.png --output output/deer --elevation 0  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/drum.png --output output/drum --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/drum2.png --output output/drum2 --elevation 15  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 1.5 --input testset/elephant.png --output output/elephant --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 1.5 --input testset/flower.png --output output/flower --elevation 0  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/flower2.png --output output/flower2 --elevation 0  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/forest.png --output output/forest --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/giraffe.png --output output/giraffe --elevation 10  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/grandfather.png --output output/grandfather --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/ground.png --output output/ground --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 1.5 --input testset/halloween.png --output output/halloween --elevation 15  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/hat.png --output output/hat --elevation 30  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/head.png --output output/head --elevation 15  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/house.png --output output/house --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/kunkun.png --output output/kunkun --elevation 30  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/lotus_seed.png --output output/lotus_seed --elevation 30  --crop_size 150
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/lunch_bag.png --output output/lunch_bag --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/milk.png --output output/milk --elevation 20  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/monkey.png --output output/monkey --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/oil.png --output output/oil --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 1.5 --input testset/poro.png --output output/poro --elevation 20  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/school_bus1.png --output output/school_bus1 --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/school_bus2.png --output output/school_bus2 --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/shed.png --output output/shed --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/shoe.png --output output/shoe --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/sofa.png --output output/sofa --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/sofa2.png --output output/sofa2 --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 1.5 --input testset/steak.png --output output/steak --elevation 30  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/teapot.png --output output/teapot --elevation 0  --crop_size 180
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/teapot2.png --output output/teapot2 --elevation 20  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/toaster.png --output output/toaster --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/turtle.png --output output/turtle --elevation 30  --crop_size -1
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/vase.png --output output/vase --elevation 10  --crop_size 200
python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt --sample_num 4 --cfg_scale 2.0 --input testset/wisky.png --output output/wisky --elevation 30  --crop_size 180
